# Generated by Django 5.0.3 on 2024-03-21 16:29

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('origin_name', models.CharField(max_length=50)),
                ('size', models.IntegerField(null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('downloaded_at', models.DateField(null=True)),
                ('comment', models.TextField(blank=True, max_length=100, null=True)),
                ('file', models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='storage'), upload_to='')),
            ],
        ),
    ]
