# Generated by Django 5.0.3 on 2024-03-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='storage_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='origin_name',
            field=models.CharField(max_length=100),
        ),
    ]
