# Generated by Django 5.0.3 on 2024-03-22 17:12

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_filemodel_storage_name_alter_filemodel_origin_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filemodel',
            old_name='storage_name',
            new_name='custom_name',
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='file',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='files/storage'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='origin_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
