# Generated by Django 5.0.3 on 2024-03-22 17:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_rename_storage_name_filemodel_custom_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FileModel',
            new_name='File',
        ),
    ]
