# Generated by Django 5.0.3 on 2024-03-23 03:15

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_rename_filemodel_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='file_storage'), upload_to=''),
        ),
    ]
