# Generated by Django 5.0.3 on 2024-03-23 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_alter_file_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='public_link',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
